### ISSUE TITLE
Crashing "Joining a custom map"

### ISSUE THREAD

**Issue by Martaain** [Stanbroek/RocketPlugin#11]
- BakkesMod Version:  140
- RocketPlugin Version:  0.6.5.14

**Describe the bug**  
Whenever my friends press "Joining a custom map" it crashes their game.

**To Reproduce**  
1.  Install Rocket Plugin. 
2.  Install a custom map.
3.  Press "Joining a custom map"

**Comment by Stanbroek** [comment]
Could you send me his crash dump, they are located in: 
```My Documents/My Games/rocketleague/TAGame/Logs```
Now upload a few (1-3, NOT ALL) of the newest crashdump files  (.dmp) from there here.

![folder example](https://i.imgur.com/OkglN9o.png)
