### ISSUE TITLE
Rocket Plugin GUI non functional 

### ISSUE THREAD

**Issue by fr05ty125** [Stanbroek/RocketPlugin#12]
- BakkesMod Version:  140
- RocketPlugin Version: Unware on how to find version number.

**Describe the bug**  
When using bakkes mod, i am unable to open the rocket plugin GUI. When pressing the button nothing happens at all.
This is with a fresh uninstalled/reinstalled bakkes mod on administrator mode, with whitelisting on all anti virus and firewalls. I attempted to install rocket plugin using the bakkes mod plugin website feature that runs a cmd, manually installing the files and attempting to download the mod through bakkes mod console using command "bpm_install 108"
using the command replies with "cvar install does not exist?"

Ive attempted to run the GUI plugin manager but the same problems occurs when pressing the button to launch the gui, nothing occurs.

I understand this might not have anything to do with the plugin itself but bakkes mod itself, but i was unable to find a bakkes mod discord to post in or an offical help page other than the main troubleshooting website. 
I
let me know if you would like extra information or contact me on discord Benn#1558

**Comment by ambid17** [comment]
@fr05ty125 Bakkesmod discord: https://discord.com/invite/HsM6kAR

**Comment by daftpenguin** [comment]
Sounds like plugin manager is not loading. Try running `plugin load pluginmanager` in F6. If you get the "LoadLibrary returned NULL" problem: https://bakkesmod.fandom.com/wiki/Troubleshooting#Cannot_open_the_plugin_manager_ingame_and_the_console_prints_.22LoadLibrary_returned_NULL.2C_..._Error_code:_126.22.
