### ISSUE TITLE
Unable to host match after Season 3 update

### ISSUE THREAD

**Issue by brad46west** [Stanbroek/RocketPlugin#13]
- BakkesMod Version:  141
- RocketPlugin Version:  0.6.5

**Describe the bug**  
hosting server fails after using host button with correct settings

**To Reproduce**  
1.  open plugin GUI
2.  type in hamachi ipv4 address and try to host

**Expected behavior**  
map begins to open and becomes joinable
**Screenshots**  
https://user-images.githubusercontent.com/82294968/114288258-e9fa6980-9a22-11eb-844d-7d0dfac32143.mp4
**Additional context**  
the host ability seems to be disabled? worked before season 3 update with same settings

not sure how github works, but if replying to this isnt a thing, direct message me on discord, bradwest#3719

**Comment by brad46west** [comment]
i am aware that, that isnt a proper ip address, but i didnt want to post that to a public form, the proper ip address was used while attempting to host

**Comment by brad46west** [comment]
@Stanbroek you tagged as fixed, where can i find an update?

**Comment by Stanbroek** [comment]
This issue is still open, which means that it is still an active issue and the description of the tag says:
> Fix will be pushed next update

which means that this specific issue was been addressed and will be pushed with the next update.

**Comment by juwbr** [comment]
I really do not want to bother you @Stanbroek, but do you have an idea, how long it will take to fix this?
