### ISSUE TITLE
Minor inconsistencies across platforms

### ISSUE THREAD

**Issue by Naoki95957** [Stanbroek/RocketPlugin#14]
- BakkesMod Version:  
![bmv](https://user-images.githubusercontent.com/9288548/130154882-084ae9b9-fc87-433e-9455-34e9c2c6c215.png)

- RocketPlugin Version:  0.6.7

Inconsistencies across Epic and Steam platforms.

Missing 'copy map and restart' button:
When under the 'Joining a local game' section of the GUI, selecting a custom map provides the button to copy map and restart. However on Epic this button remains a 'join.' When pressing a red banner appears however _**nothing**_ appears until after the game responds from timeout. 

cvar usage:
A further bug discovered is that the path setting doesn't appear to effect this version of rocket plugin. I've noticed both `rp_workshop_path` and `rp_custom_path` do not appear to effect the plugin and even if set to the same on both platforms, they can point to different folders independently. I don't know if the cause of this something of the game, of the plugin, or maybe even bakkesmod. 

**To Reproduce**  
Steps to reproduce the behavior for **missing 'copy map and restart' button:**  
1. Set up bakkes/rocket plugin on Epic
2. Install UDK map files in the mods folder
3. Attempt to select a custom map 

Steps to reproduce the behavior for **cvar usage:**  
1. Set up bakkes/rocket plugin on Epic or Steam
2. Change the cvar for either `rp_custom_path` or `rp_workshop_path`
3. Open GUI and select 'enable custom map' under hosting or 'joining a custom map' under joining
4. You should notice default paths for workshop and custom still remain default despite the cvar being set. 

**Expected behavior**  
 - Copy map and restart should appear on epic and allow players to convert udk files into upk files for play. 
 - After setting the cvar, the plugin should be able to read the directory set and make use of the maps. 

**Screenshots**  
Missing "copy map and restart" button (left is Steam, right is Epic)
![steam-epic](https://user-images.githubusercontent.com/9288548/130152583-da2eb35b-b659-4518-9216-b6219cc15af9.png)

Here's an example with a single map (on Epic):
![udk_test](https://user-images.githubusercontent.com/9288548/130154576-36d7e186-4f5f-4492-9074-30df31162d9a.png)

Cvars not effecting rocket plugin on both platforms (top is Steam, bottom is Epic): 
![custom_path](https://user-images.githubusercontent.com/9288548/130152631-423cd7e0-cff7-404d-a23e-2ee3d8e3abd4.png)

**Comment by Stanbroek** [comment]
The latest update should have fixed this.
