### ISSUE TITLE
Joining Custom Lobbies (No Copy and Restart option)

### ISSUE THREAD

**Issue by PointZera** [Stanbroek/RocketPlugin#15]
- BakkesMod Version:  153
- RocketPlugin Version:  0.6.8

**Describe the bug**  
Attempting to join a hosted lobby. Paste target IPv4, Check joining custom map, select map. The copy map and restart option does not appear. Join button remains. Select join. Greeted with error loading map message

**To Reproduce**  
1.  Paste target IPv4
2.  Check joining custom map
3. Select Workshop map
4. Copy map and restart does not appear

**Expected behavior**  
the copy map and restart option should replace the join option

**Screenshots**  
![image](https://user-images.githubusercontent.com/92608060/137556271-7dcf4fb2-d0ac-43d5-a819-e331c6f81f34.png)

**Comment by Stanbroek** [comment]
The `copy map and restart` option only appears when Rocket Plugin can't load the map into Rocket League memory,
aka its a failsafe for when Rocket League breaks the signatures.

What is the "error loading map message"?

**Comment by PointZera** [comment]
![image](https://user-images.githubusercontent.com/92608060/137557685-07cb6caf-4812-4387-a461-bbb247321735.png)
I've uninstalled, Bakkesmod and the rocket plugin, unsubscribed from the map and reinstalled all the previous mentioned however when i select join the red banner with error loading map appears

**Comment by PointZera** [comment]
Furthermore, I am able to host the map and load it correctly. I also, had my friend go through the join steps to eliminate client side issues. However, he has run into the same issue

**Comment by Stanbroek** [comment]
The newest update should add more console logs for when it failed to load the map.
Could you send those if it still happens?
