### ISSUE TITLE
Cant Start Rocket League after Bakkes Update for Rocket League Version 2.14

### ISSUE THREAD

**Issue by maginator** [Stanbroek/RocketPlugin#17]
- BakkesMod Version:  163
- RocketPlugin Version:  0.7

**Describe the bug**  
Unable to start Rocket League after the Rocket League Update to 2.14.

**To Reproduce**  
1.  Update Rocket League to 2.14
2.  Update Bakkes Mod
3. Try to Start Rocket League

**Expected behavior**  
First the Game Should start but after a little Time there will be a Error Message an it would crash

**Screenshots**  
![image](https://user-images.githubusercontent.com/19614585/165519994-2cc30bc7-5e9c-4218-8310-850936131bfc.png)

**Additional context**  
I also get this in to my clipboard:
`Fatal error!

Address = 0xdba03d08 (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\plugins\serverhost.dll]
Address = 0x45496b   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x44fe86   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x45771a   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x3b09ec   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x3b10f4   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x3b0249   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x3b2713   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x39ffe6   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x44b0f3   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x43cbc6   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0x43c803   (filename not found) [in C:\Users\user\AppData\Roaming\bakkesmod\bakkesmod\dll\bakkesmod.dll]
Address = 0xf40efb31 (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf3fbf55b (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf46f2085 (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf4682b4d (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf467e24c (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf467e29a (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf4684611 (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0xf4e0cf76 (filename not found) [in P:\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe]
Address = 0x88827034 (filename not found) [in C:\WINDOWS\System32\KERNEL32.DLL]
Address = 0x8a662651 (filename not found) [in C:\WINDOWS\SYSTEM32\ntdll.dll]
Address = 0x8a662651 (filename not found) [in C:\WINDOWS\SYSTEM32\ntdll.dll]
`
I dont realy know if it is a Problem with RocketPlugin but the Picture say somethin like this

**Comment by Stanbroek** [comment]
This is a crash from [Rocket Host](https://bakkesplugins.com/plugins/view/216) which for some reason uses a file named `RocketPlugin.cpp`.
*There was an update to Rocket Host not that long ago, so I assume it is fixed now.*
