### ISSUE TITLE
Support IPv6 

### ISSUE THREAD

**Issue by ExRed** [Stanbroek/RocketPlugin#19]
- BakkesMod Version:  168
- RocketPlugin Version:  0.7.2.0

**Describe the bug**  
Is it possible to provide IPv6 support for hosting and moreso joining a game?

**To Reproduce**  
1.  Try to connect to a host that uses IPv6
2.  It says "invalid address"

**Expected behavior**  
I can paste a IPv6 address into the join section of the plugin gui and connect
![image](https://user-images.githubusercontent.com/6467676/179316846-e54517d5-f0a1-45d3-9ff2-ac5e8d6190e8.png)

**Additional context**  
My IPS only lets me port forward/host exposure using IPv6. Therefore I cannot have my friend connect to the match I hosted. Workaround: Hamachi

**Comment by Stanbroek** [comment]
Sadly not because Rocket League does not support IPv6 connections.
