### ISSUE TITLE
Crazy Rumble Not Working 

### ISSUE THREAD

**Issue by Trento88** [Stanbroek/RocketPlugin#20]
- BakkesMod Version:  169
- RocketPlugin Version:  0.7.2

**Describe the bug**  
When i turn on rumble and crazy rumble to play crazy rumble when the timer hits 0 it goes back up to the starting number (1, 2 , 3 , 4 , 5 , etc)

**To Reproduce**  
1.  Turn on rumble in rocket plugin
2.  go to gamemodes
3. Turn on crazy rumble
4. Start the game
5. In the bottom right it will go back up to the starting number

**Expected behavior**  
It is supposed to let you use the item and not go back up to the starting number when it hits 0.

**Screenshots**  
[Rocket League (64-bit, DX11, Cooked) 2022-09-05 19-50-10.zip](https://github.com/Stanbroek/RocketPlugin/files/9492379/Rocket.League.64-bit.DX11.Cooked.2022-09-05.19-50-10.zip)
Here is a video its ziped you will have to unzip it.

**Comment by Stanbroek** [comment]
Thanks for the report, it should be fixed next update.
