### ISSUE TITLE
CFG

### ISSUE THREAD

**Issue by WoIfie** [Stanbroek/RocketPlugin#23]
- BakkesMod Version:  
- RocketPlugin Version:  

**Describe the bug**  
A clear and concise description of what the bug is.well i need the cfg file and i dont

**To Reproduce**  
1.give me the cfg file  
2.  

**Expected behavior**  

**Screenshots**  
<img width="106" alt="image" src="https://user-images.githubusercontent.com/121352629/209443841-a7a8ce3c-fca9-499d-8aa3-38993c20a392.png"> 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/121352629/209443856-7f097630-346b-47bd-ac6e-fbe880cca3f2.png">

**Additional context**

**Comment by Stanbroek** [comment]
You don't need the cfg file.
