### ISSUE TITLE
Crash of Crazy rumble on rocket plugin

### ISSUE THREAD

**Issue by Ximales** [Stanbroek/RocketPlugin#24]
- BakkesMod Version:  177
- RocketPlugin Version:  0.7.2.1

**Describe the bug**  
When i launch a game with the rocket plugin and the crazy rumble enabled, i start good but when i choose a team and spawn my game shut down 5 seconds later.

**To Reproduce**  
1.  Open Rocket plugin menu and enable crazy rumble
2.  Start a game with bots and choose a team
3. Wait a moment until the game crash

**Expected behavior**  
I expected to play with bots to have fun (i also tried with or without mutators).

**Screenshots**  
Difficult for me to take a screenshot of a game crashing sorry

**Additional context**  
I launch my game with 4 all-star bots

**Comment by Stanbroek** [comment]
Should be fixed in when the update is approved.
