### ISSUE TITLE
Autofill with Bots always 6v6

### ISSUE THREAD

**Issue by kaaax0815** [Stanbroek/RocketPlugin#4]
- BakkesMod Version:  120
- RocketPlugin Version:  0.6.2

**Describe the bug**  
If i click "Autofill with Bots" but set player count  to 2. Its still 6v6

**Expected behavior**  
If i want a player count 2 i want a 1v1

**Comment by MrPh1l** [comment]
I created a pull request that fixes this bug. See here #8
