### ISSUE TITLE
Modded Rumble settings not working

### ISSUE THREAD

**Issue by bruheatmvpingu** [Stanbroek/RocketPlugin#6]
- BakkesMod Version: 06/02/2020 
- RocketPlugin Version:  1.88

**Describe the bug**  
A clear and concise description of what the bug is. When trying to use RocketPlugin Crazy Rumble, only thing that can be modified is the Rumble power up timer(10 second one) Other mods like 10x power/range/duration doesn't work

**To Reproduce**  
1.  Use Rocket Plugin and host a match
2.  Try to customise the modded rumble settings

**Expected behavior**  
A clear and concise description of what you expected to happen. Everything becoming what i modified it to become, instead of staying at normal 1x

**Screenshots**  

**Additional context**

**Comment by Stanbroek** [comment]
As far as I can tell this has to be fixed by BakkesMod, but I will leave this issue open for now.
