### ISSUE TITLE
Respawning does glitches the match

### ISSUE THREAD

**Issue by Naoki95957** [Stanbroek/RocketPlugin#9]
- Rocket League Version: 1.89
- BakkesMod Version:  130
- RocketPlugin Version:  0.6.4

**Describe the bug**  
I will list 2 bugs I'm aware of and will label them [1] and [2]* (If you'd prefer 2 separate reports lmk, I don't mind changing it):
[1] Demolish button sometimes works (mostly doesn't) and when it fails it causes major fps tank.
~~[2] UPnP scanning and forwarding no longer works. It searches for it but then after some time fails~~

**To Reproduce**  
Steps to reproduce the behavior for [1]:  
1.  Host a match
2.  Select a team or auto
3.  After kickoff timer, open Rocket Plugin and navigate to demolish. 
4.  Demolish any player (including yourself)

~~Steps to reproduce the behavior for [2]:~~
~~1.  Open Rocket Plugin on either main menu or in match~~
~~2.  Click 'search for UPnP devices'~~

**Expected behavior**  
[1] Demolish should follow up with a respawn shortly after. However the result is not spawning in with a major fps tank. I have to restart my matches to get out of this.

~~[2] Should identify the UPnP on my router. It did before just not anymore. RL Lobby still works so there is a work around here for now.~~

**Additional context**  
I really appreciate your work on this plugin. It is used by a huge number of us and I want to say thanks :)
Especially appreciated the little fix to 'copy map and restart' instead of just 'join.' It confused a lot of new people when I tried to explain it to them, but no more!

* 2nd  issue might just be isolated to me.

**Comment by Naoki95957** [comment]
This may or  may not relate to the spawning issue. It has the same results but this is from my perspective joining my laggy friend. This wasn't induced with demolish, rather, simply spawning in. 

https://youtu.be/ChXlSgu-ZLQ

**Comment by Stanbroek** [comment]
Thanks for the bug report.
For issue 1, I encounterd this with swapping teams and thought that I disabled all the functions that caused that, so this will be fixed once I find an overall fix for the not respawning thing.
For issue 2, when I enable UPnP on my router and click 'search for UPnP devices' it still find my router.

**Comment by Naoki95957** [comment]
Happy to help! That's strange and interesting for the UPnP. I wouldn't know why it works on one plugin and not the other but it's never was a big deal in that regard. I'll scratch that off for now.

**Comment by Stanbroek** [comment]
Looks like I just kept respawning the car:
https://github.com/Stanbroek/RocketPlugin/blob/master/source/RocketPlugin.cpp#L1455
https://github.com/Stanbroek/RocketPlugin/blob/master/source/RocketPlugin.cpp#L1541
